dice_spawner_node:
  ros__parameters:
    face_up: 3
    dice_size: 0.03
    random_position: false
    x_min: -0.20
    x_max: 0.20
    y_min: 0.35
    y_max: 0.70
    surface_height: 0.0
    position: [0.15, 0.5, 0.0]
    yaw: 1.4 #radians
    pips_distance: 0.26
    pip_diameter: 0.21
